selected_scheme scheme-basic
collection-fontsrecommended 1
collection-langchinese 1
collection-latex 1
collection-xetex 1
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
TEXDIR ./texlive
TEXMFCONFIG ./texlive/texmf-config
TEXMFHOME ./texlive
TEXMFLOCAL ./texlive
TEXMFSYSCONFIG ./texlive/texmf-config
TEXMFSYSVAR ./texlive/texmf-var
TEXMFVAR ./texlive/texmf-var
